import { Product } from "../Types/Product";
import ipad9 from "../assets/Images/Apple iPad 9.png";
import appleWatch9 from "../assets/Images/Apple Watch Series 9 GPS 41mm Starlight Aluminium Case.png";
import blackMagic from "../assets/Images/Blackmagic Pocket Cinema Camera.png";
import galaxyBuds from "../assets/Images/Galaxy Buds.png";
import galaxyZFold from "../assets/Images/Galaxy Z Fold5 Unlocked.png";
import iphone14pro from "../assets/Images/Iphone 14 pro 1.png";
import samsungGalaxyWatch from "../assets/Images/Samsung Galaxy Watch6 Classic 47mm Black.png";
import sonyHeadphones from "../assets/Images/Sony Headphones.png";
export const Products: Product[] = [
  {
    id: 1,
    image: ipad9,
    title: "Apple iPad 9 10.2 64GB Wi-Fi Silver (MK2L3) 2021",
    orginalPrice: 400,
    currentPrice: 398,
    category: "Mobiles",
    isNewArival: true,
    isBestSeller: false,
    isFeatured: false,
    brand: "Apple",
  },
  {
    id: 2,
    image: blackMagic,
    title: "Blackmagic Pocket Cinema Camera 6k",
    orginalPrice: 2535,
    currentPrice: 2535,
    category: "Cameras",
    isNewArival: true,
    isBestSeller: false,
    isFeatured: false,
    brand: "Blackmagic",
  },
  {
    id: 3,
    image: appleWatch9,
    title: "Apple Watch Series 9 GPS 41mm Starlight Aluminium Case",
    orginalPrice: 399,
    currentPrice: 399,
    category: "Smart Watches",
    isNewArival: true,
    isBestSeller: false,
    isFeatured: false,
    brand: "Apple",
  },
  {
    id: 4,
    image: galaxyBuds,
    title: "Galaxy Buds FE Graphite",
    orginalPrice: 99.99,
    currentPrice: 99.99,
    category: "Headphones",
    isNewArival: false,
    isBestSeller: true,
    isFeatured: false,
    brand: "Samsung",
  },
  {
    id: 5,
    image: galaxyZFold,
    title: "Galaxy Z Fold5 Unlocked | 256GB | Phantom Black",
    orginalPrice: 1799,
    currentPrice: 1799,
    category: "Mobiles",
    isNewArival: false,
    isBestSeller: true,
    isFeatured: false,
    brand: "Samsung",
  },
  {
    id: 6,
    image: iphone14pro,
    title: "Apple iPhone 14 Pro Max 128GB Deep Purple (MQ9T3RX/A)",
    orginalPrice: 900,
    currentPrice: 900,
    category: "Mobiles",
    isNewArival: false,
    isBestSeller: true,
    isFeatured: false,
    brand: "Apple",
  },
  {
    id: 7,
    image: samsungGalaxyWatch,
    title: "Samsung Galaxy Watch6 Classic 47mm Black",
    orginalPrice: 369,
    currentPrice: 369,
    category: "Smart Watches",
    isNewArival: false,
    isBestSeller: false,
    isFeatured: true,
    brand: "Samsung",
  },
  {
    id: 8,
    image: sonyHeadphones,
    title: "Sony Headphone",
    orginalPrice: 370,
    currentPrice: 370,
    category: "Headphones",
    isNewArival: false,
    isBestSeller: false,
    isFeatured: true,
    brand: "Sony",
  },
];
